name: SonarQube-Scanning
on:
  push:
    branches:
      - v2-branch
  pull_request:
    branches:
      - v2-branch
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: SonarScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sesvc.shell.com
